# Generated by Django 4.0.6 on 2022-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparat_id', models.CharField(max_length=15)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
