# Generated by Django 4.0.6 on 2022-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='time',
            new_name='packet_time',
        ),
    ]
